name: 'Saved Cloudflare config to Git'
description: 'A GitHub Action that saves Cloudflare zone configuration (DNS, rulesets, settings) to versioned JSON files in your repository.'
author: 'pronamic'

branding:
  icon: 'download-cloud'
  color: 'orange'

inputs:
  api_token:
    description: 'Cloudflare API token with read permissions for the target zone'
    required: true
  zone_id:
    description: 'Cloudflare Zone ID to export'
    required: true
  directory:
    description: 'Directory where the Cloudflare configuration files will be stored (default: cloudflare-config).'
    required: false
    default: 'cloudflare-config'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run save script
      run: php ${{ github.action_path }}/save.php
      shell: bash
      env:
        INPUT_API_TOKEN: ${{ inputs.api_token }}
        INPUT_ZONE_ID: ${{ inputs.zone_id }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
